
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect
spring.devtools.restart.enabled=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

cliente.origin.www=${CLIENT_ORIGIN_WWW}
cliente.origin.sem.www=${CLIENT_ORIGIN_SEM_WWW}

cliente.origin=${CLIENT_ORIGIN_WWW}

server.port=9090

spring.jackson.time-zone=Europe/London

#Configura��es de e-mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mot.motorcycle.uk@gmail.com
spring.mail.password=vypr jszh gahi awla
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true